name: PvpCage
main: com.noname.pvpcage.PvPCage
version: 1.1 FULL
description: Drop!
authors: [dekros987, TheTonsOfCode]
#depend: [ProtocolLib]
commands:
    cage:
        description: glowna komenda z dropem